### ISSUE TITLE
String to array report error after installation

### ISSUE THREAD

**Issue by sylink** [magemojo/m2-ce-splitdb#12]
Production site, report below after installation, can't load at all:

```
  www-data@servicepod-67889f484-jzgcm:~/public_html/var/report$ cat 624172892115
{"0":"Notice: Array to string conversion in \/srv\/public_html\/app\/code\/MageMojo\/SplitDb\/Adapter\/Pdo\/Mysql.php on line 307","1":"#0 \/srv\/public_html\/app\/code\/MageMojo\/SplitDb\/Adapter\/Pdo\/Mysql.php(307): Magento\\Framework\\App\\ErrorHandler->handler(8, 'Array to string...', '\/srv\/public_htm...', 307, Array)\n#1 \/srv\/public_html\/app\/code\/MageMojo\/SplitDb\/Adapter\/Pdo\/Mysql.php(137): MageMojo\\SplitDb\\Adapter\\Pdo\\Mysql->_dsn('SHOW TABLE STAT...')\n#2 \/srv\/public_html\/app\/code\/MageMojo\/SplitDb\/Adapter\/Pdo\/Mysql.php(716): MageMojo\\SplitDb\\Adapter\\Pdo\\Mysql->_connect('SHOW TABLE STAT...')\n#3 \/srv\/public_html\/vendor\/magento\/framework\/DB\/Adapter\/Pdo\/Mysql.php(435): MageMojo\\SplitDb\\Adapter\\Pdo\\Mysql->query('SHOW TABLE STAT...')\n#4 \/srv\/public_html\/vendor\/magento\/framework\/DB\/Adapter\/Pdo\/Mysql.php(457): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->rawQuery('SHOW TABLE STAT...')\n#5 \/srv\/public_html\/vendor\/magento\/framework\/DB\/Adapter\/Pdo\/Mysql.php(1132): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->rawFetchRow('SHOW TABLE STAT...')\n#6 \/srv\/public_html\/vendor\/magento\/framework\/DB\/Adapter\/Pdo\/Mysql.php(2549): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->showTableStatus('setup_module', NULL)\n#7 \/srv\/public_html\/vendor\/magento\/framework\/Module\/ModuleResource.php(60): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->isTableExists('setup_module')\n#8 \/srv\/public_html\/vendor\/magento\/framework\/Module\/ModuleResource.php(86): Magento\\Framework\\Module\\ModuleResource->_loadVersion('db')\n#9 \/srv\/public_html\/vendor\/magento\/framework\/Module\/DbVersionInfo.php(53): Magento\\Framework\\Module\\ModuleResource->getDbVersion('Amasty_Base')\n#10 \/srv\/public_html\/vendor\/magento\/framework\/Module\/DbVersionInfo.php(77): Magento\\Framework\\Module\\DbVersionInfo->isSchemaUpToDate('Amasty_Base')\n#11 \/srv\/public_html\/vendor\/magento\/framework\/Module\/Plugin\/DbStatusValidator.php(120): Magento\\Framework\\Module\\DbVersionInfo->getDbVersionErrors()\n#12 \/srv\/public_html\/vendor\/magento\/framework\/Module\/Plugin\/DbStatusValidator.php(53): Magento\\Framework\\Module\\Plugin\\DbStatusValidator->getGroupedDbVersionErrors()\n#13 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(121): Magento\\Framework\\Module\\Plugin\\DbStatusValidator->beforeDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Magento\\Framework\\App\\Request\\Http))\n#14 \/srv\/public_html\/vendor\/amasty\/finder\/Plugin\/FrontController\/Redirect.php(81): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#15 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Amasty\\Finder\\Plugin\\FrontController\\Redirect->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#16 \/srv\/public_html\/vendor\/mirasvit\/module-cache-warmer\/src\/CacheWarmer\/Plugin\/Debug\/OnHitPlugin.php(131): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#17 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Mirasvit\\CacheWarmer\\Plugin\\Debug\\OnHitPlugin->aroundAroundDispatch(Object(Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#18 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#19 \/srv\/public_html\/generated\/code\/Magento\/PageCache\/Model\/App\/FrontController\/BuiltinPlugin\/Interceptor.php(26): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin\\Interceptor->___callPlugins('aroundDispatch', Array, NULL)\n#20 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin\\Interceptor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#22 \/srv\/public_html\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#23 \/srv\/public_html\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#24 \/srv\/public_html\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#25 \/srv\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#26 \/srv\/public_html\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#27 {main}","url":"\/1-12-kawasaki-kx450f-dirt-bike-2012-57483.html","script_name":"\/index.php"}www-data@servicepod-67889f484-jzgcm:~/public_html/var/report$
```

**Comment by rafaelstz** [comment]
Hi @sylink ,
I was able to simulate it, then I did some changes and I merged this PR https://github.com/magemojo/m2-ce-splitdb/pull/13 . If the issue persists please let me know your M2 version and how could I simulate the issue.
